#ifndef CONSTANTS_H
#define CONSTANTS_H


#define BLUE_ROBOT_COUNT 6
#define YELLOW_ROBOT_COUNT 6

#define ROBOT_COUNT (BLUE_ROBOT_COUNT+YELLOW_ROBOT_COUNT)
#define MAX_ROBOT_COUNT 12 //dont change

#endif //CONSTANTS_H

